spring.application.name=springboot_mvc_demo
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:file:/Users/Prachi Mehra/Downloads/inmemorydb/db
spring.datasource.username=prachi18
spring.datasource.password=6969
spring.jpa.hibernate.ddl-auto=create

